### ISSUE TITLE
Check/improve handling when token loaded from file

### ISSUE THREAD

**Issue by jennybc** [jennybc/googlesheets#124]
@jzhaoo I modified `gs_auth()` to explicitly take the token from a file. This was necessary/nice in order to put `gs_auth()` under testing and to test the new `gs_user()` function. I worry that I did it in a rather hacky way. Reading source files re: oauth caching over in `httr` made me suspect there is a more official way to do this. Can you have a look at that and see if you can make this nicer? Our first application is obviously in testing but this is really quite relevant to various applications and examples we plan, where interactive authentication will never be possible. This is related to #84.

BTW is there a good reason we use the filename `testthat/googlesheets_token.rds` instead of `testthat/.httr-oauth`? Also, where is the code for creating that file? It will eventually become invalid and we'll need to get a new one, re-encrypt, update on Travis, etc. That process should be documented.

**Comment by jzhaoo** [comment]
The filename doesn't matter but I think having the extension `.rds` makes things clearer and tells us this token can be read with `readRDS()` and stored directly in the R session to be used. There is a difference between a token saved through `saveRDS()` vs `httr`.

`.httr-oauth` saved by `httr` (through browser) can be read using `readRDS()` but additional fiddling is necessary before it can be used since the credentials are stored within a long numeric hash. 

```
> token <- readRDS(".httr-oauth")
> token
$faa68f85c8290ff6d9f1ac0811d605e3
<environment: 0x10b3d6040>
attr(,"class")
[1] "Token2.0" "Token"    "R6"  
```

I will document the process of token encryption.

**Comment by jennybc** [comment]
So you are reinforcing that my hunch that my modification of `gs_auth()` is probably not designed as it should be. Feel free to refine my work or we can talk about it when we meet next.
