### ISSUE TITLE
Success code not accepted

### ISSUE THREAD

**Issue by clsnyder** [jennybc/googlesheets#149]
In RStudio:
library(googlesheets)
(my_sheets <- gs_ls())

 //put in authorization code from url paste
// there was a forward slash (?significant) in the success code from google

Error message:
googlesheets Authorization error. No access token obtained. Error: is_legit_token(google_token, verbose = TRUE) is not TRUE 

Close RStudio and retry
library(googlesheets)
(my_sheets <- gs_ls())

// results
Error: is_legit_token(google_token, verbose = TRUE) is not TRUE

**Comment by jennybc** [comment]
Can you help me understand exactly what you mean by this:

> //put in authorization code from url paste
> // there was a forward slash (?significant) in the success code from google

Specifically, I'm not sure what you mean by "put in authorization code from url paste"?

That's where the problem is. We have somehow NOT obtained a good token. Hence the error. Then that is getting cached in `.httr-oauth`, which gets re-loaded, which causes the next error from `is_legit_token()`.

You can always redo authentication via `gs_auth(new_user = TRUE)` or by removing `.httr-oauth` from your working directory (see via `getwd()`) and then doing anything that requires authentication.
