### ISSUE TITLE
Registering a Sheet Hangs R

### ISSUE THREAD

**Issue by kyeoh** [jennybc/googlesheets#153]
I've successfully authenticated to Google Sheets using googlesheets, and can view sheets available to me using gs_ls().

I tried using using gs_title('title of sheet') where it writes:
Sheet successfully identifed: "title of sheet", but R just hangs there.

I also tried gs_url('https://docs.google.com/spreadsheets/d/1BzfL0kZUz1TsI5zxJF1WNF01IxvC67FbOJUiiGMZ_mQ/')
 but the same thing happened - 
Authentication will be used.
Sheet successfully identifed: "test-gs-gapminder"

And then R stops responding.

I've tested both on a Windows and CentOS environment, and have gotten the same results.

Any ideas here?

**Comment by jennybc** [comment]
**UPDATE** I wrote all the stuff below and, when trying to give you code for my last request ... can't access the Sheets API myself. I think it might be down? I'll leave these troubleshooting ideas here in case this hypothesis turns out to be false.

Puzzling. I have certainly had **intermittent** experiences like you describe that, I assume, are due to something happening on the server side. It has never persisted or been reproducible.

Given that you see on two different systems:

Are they truly different machines? Like there's no VM business going on here?

Are both machines on the same network? I am out of my depth there but could it be some sort of network port blocking thing?

You're not using RStudio server or anything, are you?

Can you delete any `.httr-ouath` file in working directory and try to access a public sheet w/o any authentication? I'd be interested to know if such a request works.

*was going to insert working code here, but I can't reach Sheets right now either*

**Comment by kyeoh** [comment]
They are two truly different machines, one is local and the other is run on AWS EC2.

Both machines are in the same VPN, so it might be a port blocking thing - how can I troubleshoot that aspect?

On my Windows machine I'm using RStudio, and am using the .httr-oauth I generated from my Windows machine on my CentOS machine, because I could not figure out how to auth from the command line (no browser).

I tried deleting the .httr-oauth file and accessing a public sheet, but this did not work either
````
    Authentication will not be used.
    Worksheets feed constructed with public visibility
````
After that, the same thing happened.

**Comment by jennybc** [comment]
I really think the Sheets REST API is down. I cannot access it. No evidence that they have any sort of proper "status page" or feed, but have tweeted at @GoogleAppsDev to ask for a way to query status and if it's down.

**Comment by kyeoh** [comment]
Agreed! I just tested on my home computer which is on a different network and had the same issue.  
Thanks for your responses!  I'll try again when it's back up.

**Comment by jennybc** [comment]
This fresh question on stackoverflow suggests it's not just us / this package that's having problems.

http://stackoverflow.com/questions/31708602/spreadsheet-api-hangs-forever

**Comment by ReportMort** [comment]
Same issue for me. I tried deleting my .httr-oauth file and converting to a public sheet, but no luck either.

**Comment by jennybc** [comment]
OK now I know where to look this up. Yes the API is down for everyone.

https://code.google.com/a/google.com/p/apps-api-issues/issues/detail?id=3939

**Comment by jennybc** [comment]
Reopening so easier for others to find  ...

**Comment by jennybc** [comment]
Just saw this on the official issue tracker:

> Thanks everyone for raising the issue. We have found the source of the problem and hope to roll out a fix quickly.

**Comment by jennybc** [comment]
The outage appears to be over. :tada:
