### ISSUE TITLE
Tests fail for me

### ISSUE THREAD

**Issue by trestletech** [jennybc/googlesheets#170]
As of 2022-02-03, the googlesheets package has been archived on CRAN.
I'm closing all issues and pull requests prior to archiving this GitHub repo.

Learn more at:

<https://github.com/jennybc/googlesheets#readme>

**Comment by jennybc** [comment]
You're right ... it's definitely not set up for people other than me to run the tests. You're the first person who has wanted to. Will work on it.

Here's the build section of .Rproj:

```
BuildType: Package
PackageUseDevtools: Yes
PackageInstallArgs: --no-multiarch --with-keep.source --library="/Users/jenny/resources/R/library" --html
PackageRoxygenize: rd,namespace,vignette
```

I had not committed that because the library is hard-wired to something specific to me and I didn't know if it was worse to provide or not?

**Comment by trestletech** [comment]
Oh, ok. I didn't know if you were doing anything fancy in `CMD check`. May not be worth checking in, then.

Obviously no rush on this. I was just going to whittle away at the `get0`/R 3.2 issue while I was downloading R but I wanted to make sure I wasn't breaking your package as I went.
