### ISSUE TITLE
client error: (400) Bad Request

### ISSUE THREAD

**Issue by Deleetdk** [jennybc/googlesheets#172]
I am unable to register any googlesheet.

E.g.

    gs_url("https://docs.google.com/spreadsheet/ccc?key=0AoYWmgpqFzdsdEpWT0MyZTVfLTVvY0xSd0NUUkVDVlE")
    gs_key("0AoYWmgpqFzdsdEpWT0MyZTVfLTVvY0xSd0NUUkVDVlE")

These sheets are public.

Full error output:
    >gs_url("https://docs.google.com/spreadsheet/ccc?key=0AoYWmgpqFzdsdEpWT0MyZTVfLTVvY0xSd0NUUkVDVlE")
    Sheet-identifying info appears to be a browser URL.
    googlesheets will attempt to extract sheet key from the URL.
    Putative key: 0AoYWmgpqFzdsdEpWT0MyZTVfLTVvY0xSd0NUUkVDVlE
    Authentication will not be used.
    Worksheets feed constructed with public visibility
    Error in gsheets_GET(x) : client error: (400) Bad Request
    >gs_key("0AoYWmgpqFzdsdEpWT0MyZTVfLTVvY0xSd0NUUkVDVlE")
    Authentication will not be used.
    Worksheets feed constructed with public visibility
    Error in gsheets_GET(x) : client error: (400) Bad Request

**Comment by jennybc** [comment]
What happens when you do this:

``` r
library(googlesheets)
gs_gap()
#>                   Spreadsheet title: test-gs-gapminder
#>                  Spreadsheet author: rpackagetest
#>   Date of googlesheets registration: 2015-09-29 14:50:45 GMT
#>     Date of last spreadsheet update: 2015-04-22 18:27:11 GMT
#>                          visibility: public
#>                         permissions: rw
#>                             version: new
#> 
#> Contains 5 worksheets:
#> (Title): (Nominal worksheet extent as rows x columns)
#> Africa: 625 x 6
#> Americas: 301 x 6
#> Asia: 397 x 6
#> Europe: 361 x 6
#> Oceania: 25 x 6
#> 
#> Key: 1BzfL0kZUz1TsI5zxJF1WNF01IxvC67FbOJUiiGMZ_mQ
#> Browser URL: https://docs.google.com/spreadsheets/d/1BzfL0kZUz1TsI5zxJF1WNF01IxvC67FbOJUiiGMZ_mQ/
```

Google Docs had trouble yesterday -- I have no idea if that created intermittent problems accessing Sheets?

**Comment by Deleetdk** [comment]
That works fine.

> gs_gap()
                  Spreadsheet title: test-gs-gapminder
                 Spreadsheet author: rpackagetest
  Date of googlesheets registration: 2015-09-29 15:39:01 GMT
    Date of last spreadsheet update: 2015-04-22 18:27:11 GMT
                         visibility: public
                        permissions: rw
                            version: new

>Contains 5 worksheets:
(Title): (Nominal worksheet extent as rows x columns)
Africa: 625 x 6
Americas: 301 x 6
Asia: 397 x 6
Europe: 361 x 6
Oceania: 25 x 6

>Key: 1BzfL0kZUz1TsI5zxJF1WNF01IxvC67FbOJUiiGMZ_mQ
Browser URL: https://docs.google.com/spreadsheets/d/1BzfL0kZUz1TsI5zxJF1WNF01IxvC67FbOJUiiGMZ_mQ/

**Comment by jennybc** [comment]
OK so then we can no longer say that you "can't register any googlesheet". It's something about *that* Sheet.

Can you access this sheet in the browser?

Is it "published to the web"? __Note that is different from "public on the web"__ and is very important for API access. Or do you expect to access it because it is private but you have permission?

If you control this Sheet, I recommend you convert it from an "old" Sheet to  "new" Sheet. The URL in your first message makes me suspect it's one of the few old Sheets still around ...

https://support.google.com/docs/answer/3544847?hl=en

**Comment by Deleetdk** [comment]
>Can you access this sheet in the browser?

Of course. It is my sheet. :)

>Is it "published to the web"? Note that is different from "public on the web" and is very important for API access. Or do you expect to access it because it is private but you have permission?

It is public but not published (per the option in the File menu).

>If you control this Sheet, I recommend you convert it from an "old" Sheet to "new" Sheet. The URL in your first message makes me suspect it's one of the few old Sheets still around ...

I made a copy of the sheet and published it. Also did not work. But the error is different:

>gs_url("https://docs.google.com/spreadsheet/ccc?key=0AoYWmgpqFzdsdFMtLXdqdG51X29VOTlsOHByQ3dIN3c")
Sheet-identifying info appears to be a browser URL.
googlesheets will attempt to extract sheet key from the URL.
Putative key: 0AoYWmgpqFzdsdFMtLXdqdG51X29VOTlsOHByQ3dIN3c
Authentication will not be used.
Worksheets feed constructed with public visibility
Error in gsheets_GET(x) : server error: (501) Not Implemented

> gs_key("0AoYWmgpqFzdsdFMtLXdqdG51X29VOTlsOHByQ3dIN3c")
Authentication will not be used.
Worksheets feed constructed with public visibility
Error in gsheets_GET(x) : server error: (501) Not Implemented

**Comment by jennybc** [comment]
If it is public but not published you will have to access it with private visibility. You can't access public but not published Sheets via the API with public visibility:

https://developers.google.com/google-apps/spreadsheets/worksheets#sheets_api_urls_visibilities_and_projections

But the error message indicates we are still accessing with public visibility. What happens if you explicitly set visibility to private? E.g.

```
gs_key("YOUR KEY GOES HERE", visibility = TRUE)
```

It might also be interesting for you to call `gs_user()` in this same R session. Are you authenticated and have a valid token?

The second URL above, that is about the copy, is still telling me it's an old sheet. Conversion is a deliberate thing -- I don't think copying is even to trigger auto-conversion. But I also don't think that is necessarily our problem here. That's probably a side matter.

**Comment by Deleetdk** [comment]
I downloaded a file with the data, made a new sheet and imported my data again. That works. So apparently it was just the old version of the sheet causing the problem.

**Comment by jennybc** [comment]
Yes I am going to create a better diagnostic for the "public but not published" issue. See #163.

Old sheets are a real thorn in my side. I have attempted to keep some around for testing but Google keeps forcibly and silently converting them to new Sheets, so my tests fail. Perversely, my users are better able to cling to the old Sheets than I am. I'm just hoping they die out soon.
