### ISSUE TITLE
How does googlesheet differentiate between different google accounts?

### ISSUE THREAD

**Issue by hugeme** [jennybc/googlesheets#173]
Hi,

I experience some problems. I use a R Script on one machine successfully. The same script used on a different computer causes 
`browser <- gs_title("Funnel Daily")`

`browser<-gs_edit_cells(ws="Classic Browser", browser, input = ClassicBrowser, anchor = "A1",byrow = FALSE,
                    col_names = NULL, trim = F,verbose = TRUE)`

    Auto-refreshing stale OAuth token.
    Error in gs_lookup(., "sheet_title", verbose) : 
     "Funnel Daily" doesn't match sheet_title of any sheet returned by gs_ls() (which        should reflect user's Google Sheets home screen).
       > browser <- gs_title("Funnel Daily")
    Error in gs_lookup(., "sheet_title", verbose) : 
      "Funnel Daily" doesn't match sheet_title of any sheet returned by gs_ls() (which   should reflect user's Google Sheets home screen).`

if using `gl_ls()` I get a message about an google account which I also frequently use. So is there a way maybe via a token or so to differentiate between accounts or how can I solve that `issue`. I mean how can I force `googlesheets` to access some specific account?
Currently I'm using the `token`of the account which corresponds to `Funnel Daily`. The only possibility I can think of is that the browser-authentification was done with the account which not included `Funnel Daily`..

**Comment by jennybc** [comment]
You can use `gs_user()` to see info about the current Google token (basically ... who does Google think I am logged in as?), assuming there is one.

These tokens are, by default, cached in a file called `.httr-oauth`.

If you need more control and managing multiple Google identities, you need to explicitly store a token and then load it.

I am about to write this up clearly, since there is a developing theme here in the issues of people needing to take more control of their tokens.

You can read a draft of the most important points in issue #165.

Does that help?

**Comment by jennybc** [comment]
I have now written a vignette for people like you who have multiple Google accounts and need to really take charge of their tokens. You need to make sure you create a token while logged in with the intended Google account. Please see if reading this helps clear things up.

https://github.com/jennybc/googlesheets/blob/master/vignettes/managing-auth-tokens.md

Also, if you don't own a Sheet but have been granted access by someone else, it can be difficult to access it for the first time from the API. You certainly won't be able to register it by name if you have never visited it in the browser. Try registering it by key or URL (and it never hurts to visit it in the browser ... again, while logged in as the desired Google user).
