### ISSUE TITLE
Upload in a specific folder on google drive

### ISSUE THREAD

**Issue by anaisf66** [jennybc/googlesheets#184]
As of 2022-02-03, the googlesheets package has been archived on CRAN.
I'm closing all issues and pull requests prior to archiving this GitHub repo.

Learn more at:

<https://github.com/jennybc/googlesheets#readme>

**Comment by ericgtaylor** [comment]
Agreed. Just need to upload into a sub-directory on my google drive. Thanks!

**Comment by jennybc** [comment]
I will be working on this package this month and will try to clear a lot of things, including this.

**Comment by spsaaibi** [comment]
@jennybc This package has saved me multiple times Jenny, thanks so much. This issue specifically could be pretty useful for automated report generation inside an organization, so i'm truly looking forward to it :+1:

**Comment by dcabanillas** [comment]
Right now, it is possible to upload in a specific folder? If it is possible, could you write down some example. Thanks.

**Comment by daroczig** [comment]
@dcabanillas see #194 -- just pass the the ID of the folder where you want to put the document in the `parents` argument of the `gs_upload` fn

**Comment by jennybc** [comment]
Thanks @daroczig! Sorry I am sitting on your PR. I am working to offer more general access to query and manipulate metadata, which would probably mop up parent folder manipulation at the same time. Hence I haven't merged it. Also, I'm trying to do new things against Sheets API v3 and I think your PR is for v2 and one of the main differences appears to be how you specify parent-child relationships between directory-document.

https://developers.google.com/drive/v3/web/migration

**Comment by daroczig** [comment]
No worries, @jennybc, #194 is just a quick and dirty extension of the current `gs_upload` function of the `master` that I needed for a project of mine -- a more general solution to pass metadata to the actual query & using v3 is highly welcomed and looking forward to it :) Keep up the good work!

**Comment by toncek87** [comment]
I tried #194 , but there was a error "could not find function "gdrive_POST" " I have found it nowhere.. Could you tell me where i find this function?

**Comment by jennybc** [comment]
Your problem is because `googlesheets` has changed quite a bit internally since the PR was made. 

I think I should create a branch that just offers this in a quick-and-dirty way, so people who want it can have it now and don't have to wait for the bigger changes I want to make re: all the Google Drive calls. There would be no guarantee that the interface won't change in the near future. But I can make it work.

By way of explanation: internally most stuff happens via the Sheets API but this particular thing (putting doc into a specific folder) must happen via the Drive API. And I want to rework all the Drive calls. And add the parent directory feature while I'm at it. That's why I haven't just done this already.

**Comment by daroczig** [comment]
As a quick workaround, I think you can install an old version of the package with the patch:

```r
devtools::install_github('daroczig/googlesheets@upload-to-folder')
```

**Comment by soedr** [comment]
Hi there, first off, thanks to @jennybc for a great package! Checking to see if there is an update to being able to upload to a specific folder? Thanks!

**Comment by diegocgaona** [comment]
Thanks for the great package! Looking forward for this nice feature! :)

**Comment by jennybc** [comment]
I just wrote this in some other issue, but can't quickly find it.

The googledrive package is coming along nicely and will support working with Drive as if it's a (sort of like a) file system: https://github.com/tidyverse/googledrive. In particular, it knows about folders. We are ~1 week away from inviting people to test it out.

I will then resume work on a googlesheets reboot (https://github.com/tidyverse/googlesheets4) that wraps the new, snappier v4 API and will import all the folder-aware functionality from googledrive. This is getting sorted out this summer 🌞

**Comment by damianooldoni** [comment]
I have started few days ago using this wonderful package. This feature will be the cherry on top of the cake! :1st_place_medal:

**Comment by jennybc** [comment]
Since I haven't posted here in almost a year, I should say you can already upload or move a Google Sheet into a specific folder with googledrive at this very moment. I realize it will be lovely when that is exposed in a more Sheets-y way in googlesheets4, which is truly moving along now (so far, only reading though).

**Comment by scgough** [comment]
@jennybc Hi Jenny,
I'm coding in C# but your comment here caught my attention - Is there currently a way to specify `parents` at the point of creating a new spreadsheet or do you have to move the file after?

**Comment by jennybc** [comment]
@scgough As far as the Drive API goes, which is how I would create a new Sheet, yeah you can set `parents` at creation time:

https://developers.google.com/drive/api/v3/reference/files/create
