### ISSUE TITLE
Merging Existing Sheets or Copying Worksheets without Losing Original Formatting

### ISSUE THREAD

**Issue by WilliamsJacobD** [jennybc/googlesheets#187]
I've been testing googlesheet's abilities lately and unless I'm mistaken, it seems like you can't merge two existing sheets or create a copy of an existing worksheet without losing formatting. These might be useful operations. Otherwise, I'm very excited about this package and I appreciate all the time and effort put into it!

**Comment by jennybc** [comment]
Formatting is not available via the Sheets API, so that's not something that can be preserved or manipulated. Can you explain what you have in mind re: merging two existing sheets? Do you mean getting their data into one R object or are we talking about something that will change the state of the Google sheet itself?

**Comment by WilliamsJacobD** [comment]
Thank you very much for your reply jennybc. Yes, because formatting doesn't make its way through the API I thought maybe I could create a pre-formatted template sheet, copy the sheet through the googlesheets package, populate with data, and merge into an existing Google Sheets workbook without losing the formatting. I was just trying to automate a process that I have to do many times but it seems like I might need to create a pre-formatted template workbook with the multiple sheets already existing. Any thoughts?

**Comment by jennybc** [comment]
I don't think this is possible unless or until I use Google Apps Script instead of the REST API. With Apps Script, you have more complete access, including to formatting. I don't have any near terms plans to do that.

It is possible you could create such a formatted template in the browser, then copy it via `gs_copy()` and populate it with different data. Did you try that?
