### ISSUE TITLE
check.names for colnames

### ISSUE THREAD

**Issue by Deleetdk** [jennybc/googlesheets#208]
Sometimes columns will have sub-optimal names in the sheet. These are currently imported to R. This can result in e.g. names with spaces. How about a parameter to convert illegal characters? E.g. convert spaces to underscores.

**Comment by jennybc** [comment]
Which method of consumption are you using, i.e. which read function? I *am* contemplating an argument that gives you the choice of running the names through `make.names()` or similar.

**Comment by Deleetdk** [comment]
I used `gs_read_csv()` if that's what you mean. However, I also tried (just now) with `gs_read()`. Same problem.

**Comment by jennybc** [comment]
The only read function that currently manipulates column names is `gs_read_listfeed()` and, even then, it's because the API itself changes them, not this package. This package is moving towards the behaviour of `readr` which also never edits the column names, i.e. it's left for the user to do. But so many people expect or hope for that, it might make sense to add an argument to request processing via `make.names()`.

**Comment by Deleetdk** [comment]
Yes, implementing the use of `make.names()` or writing a simple renamer function would be very nice. Oldschool R names also use dots in names, but this can be problematic in some cases. Underscores or camel casing is generally preferable.

**Comment by jennybc** [comment]
I'm not willing to write my own column name processing function. I plan to offer two choices: Hadleyverse/readr, i.e. doing nothing, or the base solution, i.e. processing with `make.names()`. If a user wants to take it further, they can use the option that gets them as close as possible to what they want, then refine it on their own.

**Comment by jennybc** [comment]
All the read functions now have a logical `check.names` argument that defaults to `FALSE`. If you set it to `TRUE`, the column names will be sent through `make.names(..., unique = TRUE)`.

**Comment by Deleetdk** [comment]
Thanks.
