### ISSUE TITLE
server error on using googlesheets package

### ISSUE THREAD

**Issue by mau5lives** [jennybc/googlesheets#227]
Hi,

First of all , I will like to thank you guys. This package has been a big lifesaver.Great job guys :)

There is this one error I am struggling with recently.Sometimes when I am trying to access some of my google sheets, I am getting this error:
Error in gsheets_GET(the_url) : server error: (500) Internal Server Error

Sometimes, the package works perfectly , sometimes it gives me this error.

As I am running this on a AWS machine, this should not happen because of any internet issues. Can you guys please help me out.

Sorry for my bad English, not my native language :)

**Comment by jennybc** [comment]
Thanks!

This 500 error is, as it says, internal to Google's servers. It has nothing to do with googlesheets (or you or AWS). It is a Drive-wide, worldwide phenomenon that seemed to increase dramatically in early March 2016. It is also causing me great pain (and many others on various issues here!). That's why I am seriously considering building retries into the googlesheets package itself (see #225). In the meantime, I've put a function you can use yourself as a workaround in #229. That thread would probably be helpful for you to read.

**Comment by jennybc** [comment]
*Apologies if you see this notification more than once: I'm posting it on all the threads re: HTTP 500 errors*

The current dev version here on github now has up to 5 automatic retries on all GETs that result in Internal Server Error (HTTP 500). So far I have had NO trouble building vignettes, running tests, or passing on Travis! This is huge progress. Try the dev version if you've been having trouble with these errors.

```
devtools::install_github("jennybc/googlesheets")
```

It probably needs some refinement, so am happy to get feedback.

**Comment by paulditterline** [comment]
Thanks a million. I was contacting R Studio because I thought the error was with them, then I ran the app on my machine and saw the error was with googlesheets.
