### ISSUE TITLE
How to set encoding explicitly?

### ISSUE THREAD

**Issue by RoyalTS** [jennybc/googlesheets#245]
As of 2022-02-03, the googlesheets package has been archived on CRAN.
I'm closing all issues and pull requests prior to archiving this GitHub repo.

Learn more at:

<https://github.com/jennybc/googlesheets#readme>

**Comment by jennybc** [comment]
Good question. Basically, this is something from `httr` and/or `readr` that, for lack of a better idea, I'm just allowing to happen. It's not a message generate by `googlesheets`. It happens when I pass data through those packages. I'm not exactly happy with all those message myself but unless, as you say, I or the user takes charge of encoding, it seems best to be passive about it.

Which user-facing `googlesheets` function(s) are we specifically talking about?

**Comment by RoyalTS** [comment]
This is `ws_read()`

**Comment by jennybc** [comment]
`httr` just quieted some of its messaging around encoding not being supplied. I'll install the dev version soon and see if produces a happy result for us.

**Comment by RoyalTS** [comment]
It's in the latest release version now: https://cran.r-project.org/web/packages/httr/news.html
