### ISSUE TITLE
gs_read(): col_types argument has no effect for columns with NA's only

### ISSUE THREAD

**Issue by florisvdh** [jennybc/googlesheets#268]
I am dealing with several worksheets containing the same columns (variables). This is because each worksheet is filled with data by another researcher. In several worksheets, columns exist that are empty (these values should and will become 'NA' when reading into R). These columns are not the same between different worksheets. In R, I construct one dataframe that contains all the data, by reading in each worksheet with `gs_read()` and then `dplyr::union` it with the previously read data, within a loop.

Given the existence of NA columns, and the fact that those are set as the logical (lgl) data type by default (I understand that this is done by readr), I need to manually set the data type of the columns when reading the datasheet, through the `col_types` argument (in my case, most columns contain character data, sometimes integer). Although this 'data type overriding' works for columns with at least one value, I've still got the error messages that the unioning does not succeed. This is because NA columns still are set as logical. After some testing, it seems that the overriding simply cannot be done for NA columns, at least I did not succeed to do so with the col_types argument. See code below, with a workaround (using `mutate_at()`) to solve the problem for now.

```
rawdata <- rawdata %>% filter(FALSE)     # deleting previously gathered data (and provided that data types are OK now)

for (i in 5:31) {
rawdata <- questionnaire %>% gs_read(
                        ws=i,
                        skip=2,
                        col_names=vectorof40colnames,
                        col_types = paste0(paste0(rep("c",34),collapse=""),"i",paste0(rep("c",5),collapse=""))
                        ) %>%  # this line only has effect on columns with at least one value. Note: the string provided by the paste0 function is "cccccccccccccccccccccccccccccccccciccccc"
                   mutate_at(.funs=funs(as.character(.)),.cols=c(1:34,36:40)) %>%
                    union(rawdata,.)
Sys.sleep(8) # see https://github.com/jennybc/googlesheets/issues/244
}
```

**Comment by jennybc** [comment]
I am actually the one who is setting all `NA` columns to logical. `readr` would normally make them character. I'm mimicking behaviour of base R but sounds like `readr`'s default behaviour would be better for you ...

Before we go further, have you taken a look a `dplyr::bind_rows()`? I think you are basically row binding, yes? It's my impression that `bind_rows()` is more meant for this task than `union()` and might have better default behaviour for you. `bind_rows()` and `bind_cols()` are optimized for putting data frames together.

But if I'm off-base, say so, and we can discuss further.

**Comment by florisvdh** [comment]
Thanks for your explanation. Indeed, in my case it would be more convenient if `gs_read()` didn't bypass `readr`'s defaults.

I wasn't aware of the `bind_rows()` function in `dplyr`. Especially the fact that `union()` would omit identical rows between data frames is an important difference. However, I had considered that and it poses no problem in my case as there are some identifying columns (in the setup of the worksheets) that make identical rows impossible. But it is a good reason not to use `union()` if the sole purpose is to combine data frames - in general. Anyway, I think this aspect stands apart from the NA-column topic.

**Comment by jennybc** [comment]
But does `bind_rows()` finesse this character vs logical `NA` problem for you? It's pretty smart about rowbinding.

**Comment by florisvdh** [comment]
You are right! I tried `bind_rows()`, and found that it consistently makes a column of the 'character' type when the original column is logical and only has NA's in one dataframe, and when the same column is of the character type in the other original dataframe. I tested and found that this is also true even when an original *character* column only consists of NA's.

So, to conclude, `bind_rows()` handles differing data types better than `union()`.

Maybe you can make users aware of the fact that `col_types` does not affect NA columns (in the documentation of `gs_read()`), if you wish to keep it that way.

**Comment by jennybc** [comment]
Great! Glad your problem is solved.

As for your documentation suggestion ... I think I need to reconsider two things: first, should I override `readr`'s default behaviour? Maybe not. Perhaps I should just fully embrace the `readr` behaviour whatever it is. Second, even if I make all `NA` variables logical by default, I shouldn't do so if user has specifically specified column type. So I'm going to leave this open to remind myself to look at those things.

**Comment by cecabrera** [comment]
Jenny, thanks for the development on the package! Works amazing. 

I'm having that same issue refering to column types: I'd rather have `readr` default behaviour than `NA` fields as logical. Some columns  in my df are `NA` during the first 1000 rows and then there is text content (not logical). What I have done is manually writing text content on the first row so it understands its column type. 

I guess there is a better way to do this :).

**Comment by jennybc** [comment]
A couple things:

I'm going to close this (and most googlesheets issues I touch from now on) because I would never tackle a bug fix / feature like this at this point. googlesheets is sunsetted, in favour of googlesheets4 (more below).

Also, FWIW in the years since this thread started, readr itself now makes a logical column in the absence of any data. What version of readr do you have? googlesheets essentially delegates type conversion to readr, so it's possible that you'll get different (maybe better?) behaviour in googlesheets, simply by updating readr. In any case, I don't think you can ever see different behaviour in the two packages.

Below is some boilerplate content.

---

Just so you know, googlesheets (this package) is being sunsetted very soon, in favour of a successor googlesheets4:

https://github.com/tidyverse/googlesheets4

Also, depending on what you're doing, a great deal of googlesheets's functionality (this package) can be accomplished with the already-released and actively-maintained googledrive package:

https://googledrive.tidyverse.org

Anything that operates at the whole file level can be done with googledrive and, even here, has always involved calls to the Drive API instead of Sheets.

So, in terms of developing your workflow, I recommend you look towards those packages as dependencies and not googlesheets.

**Comment by florisvdh** [comment]
Thanks for the amazing work @jennybc !
