### ISSUE TITLE
Error in gs_add_row() Length Required (HTTP 411).

### ISSUE THREAD

**Issue by Javdat** [jennybc/googlesheets#269]
As of 2022-02-03, the googlesheets package has been archived on CRAN.
I'm closing all issues and pull requests prior to archiving this GitHub repo.

Learn more at:

<https://github.com/jennybc/googlesheets#readme>

**Comment by jennybc** [comment]
Are you using `gs_add_row()` to add a single row or a 2D thing?

To narrow things down, perhaps you would need to fork and add some print statements? Because we really need to know if it's the `GET()` or the `POST()` that's the problem. After the `POST()` you should see either  `Row successfully appended.` or `Unable to confirm that new row was added.` Do your log show one of those after each call?
 
One possibility is that row `i` hasn't truly been added by the time you start things with row `i+1`. Every now and then I find the API is just incredibly slow. And I could imagine that this would cause a problem.

**Comment by Javdat** [comment]
I am using it to add a single row, every minute.

I do get `Row successfully appended.` after each successful run, but not before or after the error.  

I have read that the problem might be connected with the 0 length data (no data) and to set `Content-Length: 0`.

But this should not be the case, as the same row (vector) has been successfully appended to local log file. Thus it is defiantly not an empty vector. 

The possibility of slow API sounds plausible. But, in that case should not `gs_add_row()` just overwrite row `i`, assuming that it is empty?
