### ISSUE TITLE
Forbidden (HTTP 403) when running gs_webapp_get_token()

### ISSUE THREAD

**Issue by nicw4ves** [jennybc/googlesheets#279]
As of 2022-02-03, the googlesheets package has been archived on CRAN.
I'm closing all issues and pull requests prior to archiving this GitHub repo.

Learn more at:

<https://github.com/jennybc/googlesheets#readme>

**Comment by BonnyRead** [comment]
I also get the same error message after following step by step in your 20_gs-explorer example.
I am trying to deploy my shiny application which allows the users to interact with the google sheets by my shiny app to the shinyapp.io server.
After clicking the login button, it does bring me to the authentication page and allows me to get the token.
However, the error message "Forbidden (HTTP 403)" occurs to me.
Is there any solution to it?
Due to the fact that I am not a native speaker, I apologize for my poor English in advance.

**Comment by jennybc** [comment]
Can you edit your app to reveal the output of `gs_user()` so we can verify whether it is successfully obtaining and sending a token? Or not, as it seems.  I suspect we're not holding on to the token properly. I haven't updated that app in a very long time, so it's entirely possible the problem is in my example.

@nicw4ves I don't think this has anything to do with your shiny account or verifying domain.
