### ISSUE TITLE
Calling gs_ws_new with a same-named sheet as one previously deleted

### ISSUE THREAD

**Issue by ashleylester** [jennybc/googlesheets#281]
If I call this in a loop repeatedly in a workbook containing a single sheet, named ga_output:

    gs_ws_new(gs, ws = "temp")
    gs_ws_delete(gs, ws = "ga_output")
    gs_ws_rename(gs, from = "temp", to = "ga_output")

The API returns various errors:

    Error: Worksheet temp not found.
    Error: A worksheet titled "temp" already exists, please choose a different name.

A workaround is to re-register the key for the workbook using gs_key before each call.

**Comment by jennybc** [comment]
Can you try again with a very long pause between the worksheet deletion and the rename? The Sheets back end is highly variable in terms of how long things take. So it can be hard to predict how soon you next operation can be requested.

What's the rationale for approaching this way versus, say, re-populating an existing worksheet with new data?

**Comment by ashleylester** [comment]
Yeah that's a good point, I'll try with a longer pause. Yeah that's a good question, the rationale was to see whether the Google Sheets API was any "better" with data going into a fresh worksheet in the same workbook as opposed to going into a worksheet that already existed.

It might be clutching at straws. In general it strikes me that the API is pretty mean on the size of data streams they allow into Sheets.

**Comment by jennybc** [comment]
> the API is pretty mean on the size of data streams they allow into Sheets.

Yes, what you gain in ease of set up, you lose re: performance.

**Comment by debarros** [comment]
I found a similar problem when I created a worksheet and then tried to delete it later.  This was something I implemented because I wanted to clear out a worksheet called **main** and then repopulate it, and I once had an issue where the network connection failed between those two steps.  Now, my code creates a **backup** worksheet with the desired data, then clears **main**, then loads the new data (same as in **backup**) into **main**, and then deletes **backup**.  I thought about just deleting **main** and renaming **backup** to **main**, but **main** has some formatting that I want to keep and it's easier to just clear it out and load new data than to try to recreate the formatting.  Also, after reading this, I realized that I would have encountered the same error, anyway.  

It would be cool if there were an optional parameter in the `gs_ws_delete` and `gs_ws_rename` functions that reregistered the sheet before applying the command.  However, since it would be happening inside the function, it probably wouldn't affect the registered sheet in the calling environment (but I honestly don't know enough about environments to say).  So yeah, calling `gs_key` seems to be the best option.
