### ISSUE TITLE
gs_upload cannot upload file

### ISSUE THREAD

**Issue by linjunshi** [jennybc/googlesheets#298]
As of 2022-02-03, the googlesheets package has been archived on CRAN.
I'm closing all issues and pull requests prior to archiving this GitHub repo.

Learn more at:

<https://github.com/jennybc/googlesheets#readme>

**Comment by jennybc** [comment]
@jeroenooms have you seen this curl error before and/or do you have a hunch what it means?

**Comment by jeroenooms** [comment]
This error is almost always the result of a malconfigured HTTP2 server. Is this happening when talking to the google servers, or are you using some intermedediate proxy server? Similar issues:
 
 - https://github.com/ropensci/monkeylearn/issues/14
 - https://github.com/r-hub/rhub/issues/32

A simple workaround is to disable HTTP/2 in the client by setting the `http_version` options, see here for an example: https://github.com/ropensci/monkeylearn/pull/15/files

**Comment by jennybc** [comment]
@jeroenooms Are you recommending that I make such a change in the googlesheets package itself? Re: the simple workaround.

**Comment by jeroenooms** [comment]
Do you have this problem yourself as well, or does it only happen for @linjunshi ?

If you can reproduce the problem, then it seems the server is malconfigured for HTTP/2. In this case you should report the problem the API admin, and temporary disable HTTP/2 in your package, indeed.

However, more likely the problem is due to a malconfigured proxy server on @linjunshi's network. In this case I recommend @linjunshi first tries to resolve the issue with his proxy server before we start providing workarounds for his broken network config.

**Comment by jennybc** [comment]
No this is the first I've ever heard of this, so believe it is NOT on the server side (which is Google!).

**Comment by linjunshi** [comment]
I see. I will try it in another network tomorrow, and I will report the result to you guys. Cheers.
