### ISSUE TITLE
gs_title() cannot identify my googlesheets

### ISSUE THREAD

**Issue by cowlumbus** [jennybc/googlesheets#299]
Hi Jenny,

Thanks for developing this great package. 

I have some googlesheets created a few weeks ago. It used to work ok. But now, gs_title() cannot identify my googlesheets. However, if I make some changes to the contents of googlesheet, for example, change the worksheet name from Sheet1 to Sheet2, it can identify and then I can use gs_read() to read it.

Here is the error msg:

> Error in gs_lookup(., "sheet_title", verbose) : 
>   "Cowlumbus_data" doesn't match sheet_title of any sheet returned by gs_ls() (which should reflect user's Google Sheets home screen).

I call aa = gs_ls(), and see that gs_ls() can't find Cowlumbus_data either.

Any idea?

Thanks,

cowlumbus

**Comment by jennybc** [comment]
So this is "just" one problem, because `gs_title()` uses `gs_ls()`.

Are you saying that when you look at the result of `gs_ls()` you see *some* sheets that appear on <https://spreadsheets.google.com> for you, but not others? Can you be really specific about the sequence of actions, what you expect, and what happens instead?

Personally, I know it's very easy to be logged into Google with the "wrong" account, so that's one possible way to confuse yourself. I.e. the cached token is associated with account A, but you have a browser open logged in with account B.

**Comment by cowlumbus** [comment]
Jenny, Thank you for the response. I installed the dev version and the problem is gone.  Problem solved!
