### ISSUE TITLE
Access Google Sheets without authentication

### ISSUE THREAD

**Issue by samuel-rosa** [jennybc/googlesheets#308]
I have several public sheets -- and publish new ones every day -- in a public Google Drive folder and want to build an R function that enables users to download these sheets. As such, access must be granted without the need for authentication. Is this possible in the current version of `googlesheets`?

**Comment by jennybc** [comment]
You need to publish these sheets on the web. Please note that "published on the web" is VERY DIFFERENT from "public on the web". Published means API access works, public does not imply that. This is very confusing and aggravating but there you go.

https://support.google.com/docs/answer/37579?hl=en

They will then be readable via the Sheets API, including via googlesheets.

I am in the process of a major update. Among other things, it will be much easier to determine the status of a Sheet w/r/t API.

**Comment by samuel-rosa** [comment]
OK. I think I understand the difference.

So, suppose I have PUBLISHED several sheets and that all of these sheets are in a PUBLIC folder in my Google Drive. Would someone be able to run `googlesheets::gs_ls()` (or any other function) to get a list of the sheets that I have PUBLISHED and then choose which ones to download?

**Comment by jennybc** [comment]
In general, a sheet you don't own doesn't show up in `gs_ls()` unless you have visited it in the browser. Basically, it would need to appear for that person here:

https://docs.google.com/spreadsheets

in order for us to retrieve it when we list a person's Sheets.  There might be some other triggering conditions, but the above is my current best guess. I'd be happy to learn I was wrong!

So if you want people to access these Sheets via API and this is their first or sole contact, you must find a way to get a URL or Sheet id or key into their hands and their code.

@LucyMcGowan is working with me to develop a companion package for Google Drive. It will be on GitHub soon. And it will probably help a lot because you might only need to deliver a link to the public folder to you users. Then, via the Drive API, we can fetch the ids for all Sheets and we're in business.

**Comment by samuel-rosa** [comment]
Perfectly clear! I guess that until the work of @LucyMcGowan is ready, I will have to do as you said: find a way to provide the Sheet keys. I hope to hear about the the `googledrive` (????) package soon!

**Comment by mbannert** [comment]
I wonder what the state of this issue is 1+ year later.
Two of my students were looking to create a shiny app based on a public sheet, published by someone else which is why I resurrect this issue. 

Basically the a trying to do something like @jennybc 's example here: https://github.com/jennybc/googlesheets/blob/master/inst/shiny-examples/01_read-public-sheet/server.R

I do understand this example only works with a build in document, by I am trying to understand whether there is any auth going on for this. Basically they want to use the document described over here: https://github.com/mbannert/boar-2018/issues/1

Admittedly an ugly document, but it will be a nice tidyverse exercise :)

**Comment by jennybc** [comment]
I responded over in https://github.com/mbannert/boar-2018/issues/1 with a demo using googlesheets4.

**Comment by mbannert** [comment]
Thanks a ton. Also for your beautiful assist to help me show / advertise how the open source community and working together on github works.
