### ISSUE TITLE
gs_key() fails to load older sheets

### ISSUE THREAD

**Issue by gnishihara** [jennybc/googlesheets#314]
I really appreciate the work on this project!

This issue is probably related to #189 . 

When there are more than 500 spreadsheets, gs_key() returns the following error:

**Error in gs_lookup(., "sheet_key", verbose) :   "..." doesn't match sheet_key of any sheet returned by gs_ls() (which should reflect user's Google Sheets home screen).**

This makes it impossible to load a sheet, directly with the sheet_key.

Is there any  alternative?

Note: I erased my sheet key from the above example and replaced it with "...", since the sheet is not public.

**Comment by jennybc** [comment]
googlesheets2 😉 is under active development. Since I last did maintenance here, there is a new, vastly improved Sheets API, which googlesheets2 calls. Also, I'm working with @LucyDMcGowan to develop a Google Drive client at the same time. googlesheets2 can then use that to offer more sophisticated file and folder handling. So there is hope on the horizon.

That said, what about today? If you know the key, seems like you shouldn't need lookup. Have you tried using `gs_key()` with `lookup = FALSE`? You might have to set `visibility` as well. But I feel like you should be able to prevent lookup entirely. (The new API also makes this much smoother).

**Comment by gnishihara** [comment]
Fantastic! I got it to work by setting `lookup=FALSE` and `visibility="private"` for the private sheet. I look forward to trying out `googlesheets2`.
