### ISSUE TITLE
gs_key() for old sheets resulting in Bad Request (HTTP 400)

### ISSUE THREAD

**Issue by datagym-no** [jennybc/googlesheets#322]
As of 2022-02-03, the googlesheets package has been archived on CRAN.
I'm closing all issues and pull requests prior to archiving this GitHub repo.

Learn more at:

<https://github.com/jennybc/googlesheets#readme>

**Comment by jennybc** [comment]
I had convinced myself that "old" sheets were gone. They still live? 😱

Are you interested in making a PR with a helper function that gets a "new" key for "old" sheets? I know you may have a lot of them on your hands, but there are very rare now, so I don't really want to bake any more support for them into existing functions.

Re: `lookup = TRUE`, I honestly can't remember at this point but I also don't think I can really change that now. I am working on a Google Drive client right now (https://github.com/tidyverse/googledrive), which is a pre-requisite for a googlesheets reboot (https://github.com/tidyverse/googlesheets4) that wraps the new v4 API, which is much nicer.

**Comment by dmi3kno** [comment]
Just two years later (same day!) I am submitting PR for this. I followed your advice and created auxiliary function instead of building it into existing sheet registration chain of event (although it should be possible to catch Bad Request:400 and try and deal with it then).

I know your efforts shifted to `googlesheets4`, but there the same problem will persist, so maybe you would want a PR there as well. Let me know!

P.S. `datagym-no` is my never-launched teaching venture.

**Comment by jennybc** [comment]
Thanks! I can hopefully put googlesheets into an official "archived" mode soon, if I could ever get gargle onto CRAN 😣.

I'm pretty sure there will be no more CRAN releases of googlesheets itself. I can't imagine running that gauntlet with an API-wrapping package that is subsetted.

So old sheets still exist?
