### ISSUE TITLE
remove certain rows

### ISSUE THREAD

**Issue by cowlumbus** [jennybc/googlesheets#335]
I have the following example googlesheets:

googlesheet1:

ID  Name   Weight
1    Tom      50
2    Mike     60
3    Jerry     70

googlesheet2:

ID  Name   Weight
1    Tom     50
2    Kate     40
3    Jerry     70

I want to delete the googlesheet1 rows which are not in googlesheet2. In the example above, I want to delete the second row (2    Mike     60), the result will look like the following:

Updated googlesheet1:

ID  Name   Weight
1    Tom      50
3    Jerry     70

How to implement it in googlesheet R? I didn't find a solution online.

Thank you!

**Comment by jennybc** [comment]
If you want to cause this to happen from R, it would have to happen in 3 steps. Bring the data from both sheets into a local data frame. Do an `dplyr::anti_join()`, for example, or use any other approach you like for dropping rows present in one but not the other. Then push the edited data back up to Google Sheets in a way that overwrites the contents of the affected worksheet.

**Comment by cowlumbus** [comment]
Thanks Jenny. The solution I am looking for is the following one:
https://stackoverflow.com/questions/41695226/replace-all-contents-of-a-googlesheet-using-r-googlesheets-package

**Comment by jennybc** [comment]
Oh, in that case you might also want to look at [`googledrive::drive_update()`](http://googledrive.tidyverse.org/reference/drive_update.html). You could use it to update a Google Sheet with new data ("media" in Drive-speak), but leave the existing file id and name intact. Since it's just a Google Drive function, it doesn't know anything about worksheets. If you have multiple worksheets and you want to update one of them wholesale, `drive_update()` probably is too blunt a tool.

But now that googledrive is released, I will return to a googlesheets reboot, to exploit the new v4 API and all the file handling now available in googledrive.

**Comment by cowlumbus** [comment]
Jenny, thank you ( and your colleagues, etc.) very much for developing the wonderful googlesheet and google drive package. They saved me a lot of time.
