### ISSUE TITLE
gs_edit_cells Seems Slow

### ISSUE THREAD

**Issue by fairmantiumroche** [jennybc/googlesheets#338]
As of 2022-02-03, the googlesheets package has been archived on CRAN.
I'm closing all issues and pull requests prior to archiving this GitHub repo.

Learn more at:

<https://github.com/jennybc/googlesheets#readme>

**Comment by dsdaveh** [comment]
I ran into this as well, and found that for most use cases, I could use gs_upload(overwrite = TRUE, ...). That option preserves the doc, but wipes out anything you've added to it (other sheets, pivots, etc.). If that's a problem, I was able to work around it with a cloned sheet. It's a bit more complicated, but does the trick if you need it. The image below shows the performance comparison for gs_edit_cells and gs_upload (note its log scale, so 2 -> 100 seconds. 3 -> 1000 seconds etc). I also added a link to a doc I created with step step instructions for the cloning workaround

![gs_upload](https://user-images.githubusercontent.com/7278077/31253046-1d31cff8-a9d8-11e7-8ea8-eb972aca86bc.png)

[Automated Google Sheets updates for Charts and Pivot Tables](https://rawgit.com/dsdaveh/talks-and-tutorials/master/googlesheets_BARUG_Presentation/gs_upload_notebook.nb.html)

**Comment by fairmantiumroche** [comment]
I will give this a try and report back with my results.

Thanks for the info!

**Comment by fairmantiumroche** [comment]
Updating 1158 rows with the gs_upload() function takes only 11.49 seconds with 1158 lines.  Was taking 3030 seconds to do the same with gs_edit() (263x faster!!).

Still wish that the gs_edit() function was faster, but this kludge-y method works.

Thanks for the tip!

**Comment by rashmimehrotra** [comment]
Is there an option to use `gs_upload` for a specific worksheet? If not then the `gs_upload` method won't work, because if we have to write the other sheets back we will need to again use `gs_edit_cells` to build worksheet by worksheet.

**Comment by jennybc** [comment]
> Is there an option to use `gs_upload` for a specific worksheet?

No. It is a whole file operation.

Back when I wrote this, I don't recall their being a way to bulk upload into a specific worksheet and leave others intact. 

When I revisit (soon, I hope!) to switch to the newer API, I will keep my eyes open for this.

**Comment by dsdaveh** [comment]
> ... the gs_upload method won't work, because if we have to write the other sheets back we will need to again use gs_edit_cells to build worksheet by worksheet.

As a workaround, can you use a master spreadsheet where each tab uses IMPORTRANGE() to get information from multiple files? Each file could be written separately using gs_upload. [Example using IMPORTRANGE here](https://rawgit.com/dsdaveh/talks-and-tutorials/master/googlesheets_BARUG_Presentation/gs_upload_notebook.nb.html)

**Comment by sanjmeh** [comment]
Good suggestion but I think it won't work because IMPORTRANGE needs the URL of the file and the `gs_upload` will everytime generate a fresh URL.

**Comment by MichaelJW** [comment]
I have a workaround that I've been using successfully for a while. It also involves using `gs_upload()`, but instead of using `IMPORTRANGE()`, it runs a Google Apps Script that copies the contents of the newly-uploaded sheet to the desired worksheet within the already-existing sheet.

If you're interested, I've made a package out of this; it's on GitHub here: https://github.com/MichaelJW/gscsv - however I must warn you that, since I only just put it together, it's very rudimentary! You'll need to build the package yourself, create a Google Console project and OAuth credentials, create a Google Apps Script project... It also leaves temporary sheets sitting around in your Google Drive. 

But it does work, and it's cut the big upload tasks I do at work down from hours to minutes. Hope it helps.

**Comment by dsdaveh** [comment]
@sanjmeh the URL stays the same if you use `gs_upload(..., overwrite = TRUE)`. The example link I posted above demonstrates the use of that.

**Comment by jennybc** [comment]
> Good suggestion but I think it won't work because IMPORTRANGE needs the URL of the file and the gs_upload will everytime generate a fresh URL.

^^ This specific issue is solved by using `googledrive::drive_update()`. It will update file *contents* but leave its id intact.

**Comment by dpchurchman** [comment]
I was having trouble with trying to regularly update a larger, growing spreadsheet with gs_upload or gs_edit_cells, but have a kind of rudimentary workaround that doesn't rely on an Apps Script. I used `gs_upload("TitleofUploadSheet"...,overwrite=TRUE)` and then used IMPORTRANGE to link that uploaded sheet to my Google Sheet of interest. The problem is Google Sheets doesn't recognize the upload as editing the Google Sheet, so it works the first time, but then doesn't update the IMPORTRANGE each time I overwrite to my source Google Sheet. To trick the IMPORTRANGE into working, after gs_upload, I added:

`GSUpload <- gs_title("TitleofUploadSheet")`
`gs_ws_new("TitleofUploadSheet", row_extent=1, col_extent=1, ws_title="UpdatePlease")`

That got IMPORTRANGE to recognize my uploaded Google Sheet had changed and update.
