### ISSUE TITLE
row_extent for gs_upload()

### ISSUE THREAD

**Issue by smikeecz** [jennybc/googlesheets#341]
As of 2022-02-03, the googlesheets package has been archived on CRAN.
I'm closing all issues and pull requests prior to archiving this GitHub repo.

Learn more at:

<https://github.com/jennybc/googlesheets#readme>

**Comment by jennybc** [comment]
There's nothing I do inside `gs_upload()` that explicitly affects the default grid (meaning the number of cells regarded as existing in the Sheet). So I believe you when you say its unpredictable but I don't have some knob where I can adjust this. I'm `PUT`ting a file and that's all.

One possible explanation is that the underlying xlsx worksheets have difficult-to-see differences in which cells are populated. Cells that look empty to your eyeball can be considered "occupied" by Excel because, e.g., they have formatting applied. The [Little known Excel facts](http://readxl.tidyverse.org/articles/sheet-geometry.html#little-known-excel-facts) section of the readxl vignette explains this a bit more.

**Comment by jennybc** [comment]
You might also consider doing your xlsx upload with `googledrive::drive_upload()`. I don't have a specific reason to believe it will work better, but the google drive package uses a newer API, so it's worth a try. If you are operating on whole files, you can use the googledrive package. About half of what googlesheets does is actually accomplished via the Drive API. If you're really messing with individual worksheets and cells, then you have to use the Sheets API.

**Comment by smikeecz** [comment]
Thanks for tip, I tried `googledrive::drive_upload(type='spreadsheet')` but the total number of cells is still close to 2M limit. I can't find any parameter which would save the blank cells (like row_extent in `googlesheets::gs_ws_news()`) and don't upload them.

**Comment by jennybc** [comment]
Yeah I don't know of a solution. When I upgrade to the new Sheets API, I will keep my eyes peeled for anything useful. We really want to "auto-trim" but I can also understand why such a feature is problematic and non-existent / hard to find. I continue to think this may be driven by something non-obvious about your xlsx.
