### ISSUE TITLE
Question about Accessing Google Drive Account

### ISSUE THREAD

**Issue by AntCal90** [jennybc/googlesheets#347]
As of 2022-02-03, the googlesheets package has been archived on CRAN.
I'm closing all issues and pull requests prior to archiving this GitHub repo.

Learn more at:

<https://github.com/jennybc/googlesheets#readme>

**Comment by jennybc** [comment]
It is true that googlesheets and googledrive both request full Drive scope, so that you can use the packages to access any file you have permission for on Drive. I, as package author, however am granted no permissions to see your files.

You can read more about Drive scopes here:
https://developers.google.com/drive/v3/web/about-auth

It is NOT true that Drive scope confers permissions re: the Gmail or Calendar API.

If this clarification does not get things unstuck for you, please come back. It is possible that googledrive and an upcoming reboot of googlesheets could expose more control over scopes. And for people in your situation, maybe `https://www.googleapis.com/auth/drive.file` would be an option. I'd have to play around with it and see what sort of workflow it permits.
