### ISSUE TITLE
Error generated with private gsheet not in your Google Drive with gs_edit_cells

### ISSUE THREAD

**Issue by antoine-182** [jennybc/googlesheets#354]
As of 2022-02-03, the googlesheets package has been archived on CRAN.
I'm closing all issues and pull requests prior to archiving this GitHub repo.

Learn more at:

<https://github.com/jennybc/googlesheets#readme>

**Comment by jennybc** [comment]
This aspect of googlesheets is regrettable. Some of the awkwardness is due to awkwardness in the v3 API, but I also didn't wrap it very well in this package. A great deal of this is completely designed away in the v4 API and I have also learned a lot from this package. I am unlikely to do major refactoring of visibility matters here. I am starting a maintenance pass on this package now, but serious development effort will happen on a new package, wrapping the new Sheets API.

**Comment by antoine-182** [comment]
Ok, but for the use I am having and with patch I added, it is marvellous. Of course, I am really interested in your release of a new package. 

Wish you the best.

**Comment by jennybc** [comment]
Last time I did maintenance I think I reviewed a PR that worked on this. But it broke some tests and I didn't get to the bottom of it before moving on to something else. I am not averse to a fix! Are you going to make a PR with your fix?

**Comment by antoine-182** [comment]
Dear jennybc, I do not feel really comfortable with a PR. I am not really a developper (sorry for the late answer)
