### ISSUE TITLE
gs_edit_cells

### ISSUE THREAD

**Issue by cal65** [jennybc/googlesheets#364]
As of 2022-02-03, the googlesheets package has been archived on CRAN.
I'm closing all issues and pull requests prior to archiving this GitHub repo.

Learn more at:

<https://github.com/jennybc/googlesheets#readme>

**Comment by jennybc** [comment]
Not sure but here's more about what 409 means:

```
    409,             "ABORTED", "Concurrency conflict, such as read-modify-write conflict.",
    409,      "ALREADY_EXISTS", "The resource that a client tried to create already exists.",
```

so it could be a problem of making separate requests too soon after each other and one request is still "wrapping up" when the next one comes in.

**Comment by oguzhanogreden** [comment]
I had the same problem and I was also able to repeat it in a debugging session. The 'trick' in that session seemed to be using `gs_title('Test Sheet')` in each iteration of a loop rather than calling `sheet <- gs_title('Test Sheet')` once and then using `sheet %>% gs_edit_cells(...)`.

I wanted to note this here and I will try to produce a MWE some time soon.
