### ISSUE TITLE
HTTP 500 error only when accessing through a G-Suite account

### ISSUE THREAD

**Issue by BrianSGKim** [jennybc/googlesheets#370]
As of 2022-02-03, the googlesheets package has been archived on CRAN.
I'm closing all issues and pull requests prior to archiving this GitHub repo.

Learn more at:

<https://github.com/jennybc/googlesheets#readme>

**Comment by jennybc** [comment]
It's hard to say but a few general facts: a 500 error suggests it's on the server side and not something wrong with your token or request, etc. What exactly does it look like?

Does this have anything to do with a Team Drive? I don't think so but am just checking.

Do you need to access specific sheets and cells or could you get by with getting all the data in one sheet? Because then you could use the googledrive package, which is much newer and that method of reading will be much faster, regardless.

**Comment by WoodyWD** [comment]
I also start to get this error recently with a G Suite account. The difference on my side is I only get this error when I try to use gs_edit_cells function with large input value (around 3000 values).
