### ISSUE TITLE
Issues with Googlesheets Package 

### ISSUE THREAD

**Issue by Richard-Barrett** [jennybc/googlesheets#385]
As of 2022-02-03, the googlesheets package has been archived on CRAN.
I'm closing all issues and pull requests prior to archiving this GitHub repo.

Learn more at:

<https://github.com/jennybc/googlesheets#readme>

**Comment by jennybc** [comment]
I've never seen this error.  There is nothing named `handover` in the googlesheets package. Is there anything named that in your codebase?

Just so you know, googlesheets (this package) is being sunsetted very soon, in favour of a successor googlesheets4:

https://github.com/tidyverse/googlesheets4

The biggest caveat is that it does not yet write/modify Sheets, though it will.

Also, depending on what you're doing, a great deal of googlesheets's functionality (this package) can be accomplished with the already-released and actively-maintained googledrive package:

https://googledrive.tidyverse.org

Anything that operates at the whole file level can be done with googledrive and, even here, has always involved calls to the Drive API instead of Sheets.

So, in terms of developing your workflow, I recommend you look towards those packages as dependencies and not googlesheets.

googledrive, googlesheets4, and other packages (such as bigrquery) are using a new package for auth and I think this should make non-interactive auth easier for lots of users. Here's the central vignette for how that works:

https://gargle.r-lib.org/articles/non-interactive-auth.html

**Comment by Richard-Barrett** [comment]
Hi, I figured out the issue, the problem occurs somewhere within the Java script in regards to Oauth flow. Since Google just moved to version API4 I went ahead and just went around it and used a service account instead. Now the gs_auth looks for a specific file within my server. Furthermore, the handover sheet is a function of gs_key and gs_read. I used it to parse it with str and then make a data table with the DT package. In any event, I have solved the issue with implementing a JSON file for the google API within my company's g-suite org. 

I am now focusing on future development with googlesheets4 and google drive packages as you suggest. Thank you very much.
