### ISSUE TITLE
Google Sheets v3 API will be shut down during 2020

### ISSUE THREAD

**Issue by selesnow** [jennybc/googlesheets#395]
As of 2022-02-03, the googlesheets package has been archived on CRAN.
I'm closing all issues and pull requests prior to archiving this GitHub repo.

Learn more at:

<https://github.com/jennybc/googlesheets#readme>

**Comment by jennybc** [comment]
Yes, I got this email too.

I am releasing googlesheets4, with auth + read capability "any day now". And clearly intend to make sure it can write before the v3 API gets shut off.

I think the googlesheets package will need to be formally archived ~ March 3, 2020 (or whenever the v3 API stops working).

---

A standard set of info + links about this transition:

Just so you know, googlesheets (this package) is being sunsetted very soon, in favour of a successor googlesheets4:

https://github.com/tidyverse/googlesheets4

Also, depending on what you're doing, a great deal of googlesheets's functionality (this package) can be accomplished with the already-released and actively-maintained googledrive package:

https://googledrive.tidyverse.org

Anything that operates at the whole file level can be done with googledrive and, even here, has always involved calls to the Drive API instead of Sheets.

So, in terms of developing your workflow, I recommend you look towards those packages as dependencies and not googlesheets.

**Comment by selesnow** [comment]
Very thanks.

I use gs_read, gs_add_rows and gs_edit_cells in googlesheets.

**Comment by jennybc** [comment]
Most recent timeline:

Starting in April/May 2020, features of the v3 API will gradually be disabled and it's anticipated the API will be fully shutdown by the end of September 2020.

https://cloud.google.com/blog/products/g-suite/migrate-your-apps-use-latest-sheets-api
