### ISSUE TITLE
using googlesheets with Makefile workflow

### ISSUE THREAD

**Issue by joepowers16** [jennybc/googlesheets#396]
The googlesheets R package has been invaluable for my team's workflow, but I am unsure of how to automate the execution of R scripts after a prerequisite Google Sheet is updated. If the Google Sheet were a static csv file, then the use of a Makefile would be straightforward. Do you have advice about how (or plans to add a feature that would) integrate Google Sheets into a Makefile based workflow?

**Comment by jennybc** [comment]
A few things come to mind:

  * googledrive has new features to help you express "create this thing, if it doesn't exist yet, and update it if it does". See [this section](https://googledrive.tidyverse.org/news/index.html#overwrite-na-true-false-and-drive_put) of the v1.0.0 release notes. The file in question could be a Google Sheet.
  * The metadata you get from `googledrive::drive_get()` includes `modifiedTime`, which you could work with to determine if something has changed.
  * There is formal tooling around revision history for Drive files (which includes Sheets): <https://developers.google.com/drive/api/v3/manage-revisions>. So far googledrive doesn't offer any high-level functions around that. But if there was demand, we could.

Also ...

Just so you know, googlesheets (this package) is being sunsetted very soon, in favour of a successor googlesheets4:

https://github.com/tidyverse/googlesheets4

Also, depending on what you're doing, a great deal of googlesheets's functionality (this package) can be accomplished with the already-released and actively-maintained googledrive package:

https://googledrive.tidyverse.org

Anything that operates at the whole file level can be done with googledrive and, even here, has always involved calls to the Drive API instead of Sheets.

So, in terms of developing your workflow, I recommend you look towards those packages as dependencies and not googlesheets.

The Sheets v3 API and therefore the original googlesheets package will go offline in March 2020:

https://github.com/tidyverse/googlesheets4/issues/45

**Comment by joepowers16** [comment]
Thank you for such a prompt and thorough response. I will try implementing these changes in the coming week, and will post an update if that is helpful.
