### ISSUE TITLE
Building vignettes requires authorisation credentials interactively

### ISSUE THREAD

**Issue by davidorme** [jennybc/googlesheets#89]
Hi,

I'm trying to install (Mac OS 10.9.5, R 3.1.1) using ```devtools:::install_github()``` and the install fails when trying to build the vignette. I _think_ it is not finding ```.httr-oauth``` in the ```r authorize``` chunk, so the code in the ```r pre-clean``` chunk looks for authorisation interactively. Can the package include a default ```.httr-oauth``` file to give access for the vignette data?

Cheers
David

```
* checking for file '/private/var/folders/tv/97qk_bbs64334_xsfqpjt0k40000gn/T/Rtmp3beu9M/devtools9b722b5eba4f/googlesheets-master/DESCRIPTION' ... OK
* preparing 'googlesheets':
* checking DESCRIPTION meta-information ... OK
* installing the package to build vignettes
* creating vignettes ... ERROR
Quitting from lines 52-57 (basic-usage.Rmd) 
Error: processing vignette 'basic-usage.Rmd' failed with diagnostics:
oauth_listener() needs an interactive environment.
Execution halted
Error: Command failed (1)
```

**Comment by jennybc** [comment]
Hmmm… that is a good question. I can't ship the package w/ a `.httr-oauth` because it would be tied to one of my own Google accounts. Can I see your `devtools::install_github()` command? Can't you just set `build_vignettes = FALSE`? If you really want build the vignette locally, you could clone the repo, do something in the Project to trigger the browser-based OAuth dance to get a `.httr-oauth` file, and then install from your local clone.

FYI I do offer the current vignette in Markdown and HTML from GitHub:

http://htmlpreview.github.io/?https://raw.githubusercontent.com/jennybc/googlesheets/master/vignettes/basic-usage.html

https://github.com/jennybc/googlesheets/blob/master/vignettes/basic-usage.md

The vignette hasn't been worked on as much or as recently as the README, but obviously I do need to get this sorted out more generally.

Let me know if I should be more precise w/ exact code re: my recommendations above. For example, the cloning and installing from local clone.

**Comment by davidorme** [comment]
Sorry - clipped out the command by mistake. It was just:
```
devtools::install_github("jennybc/googlesheets")
```

I'd also missed the pass through of ```build_vignettes``` to ```install()``` from ```install_github()```. That fixes the install:
```
devtools::install_github("jennybc/googlesheets", build_vignettes=FALSE)
```

Happy to use the markdown and html vignettes. Many thanks for the quick response and for the package!

**Comment by jennybc** [comment]
I thought `build_vignettes = ` defaults to `FALSE`, so I'm kinda surprised you needed to set it to `FALSE` explicitly. But this vignette+building+authentication is an important point I'll have to figure out in the long-term….
