### ISSUE TITLE
two data fetch errors when calling from shiny

### ISSUE THREAD

**Issue by MarkEdmondson1234** [jennybc/googlesheets#95]
I'm trying to see what are the conditions for two fails of fetching sheet data, to possibly restrict listing those type of sheets, and I hope you may have come across them before so have some insight.  I guess its something to do with new vs old GoogleSheets and user permissions, or the way httr is configured on shiny.

Most of my Google Sheets data fetches work via get_via_csv(), but those that don't are:

## error 1: 
    Error in handle_url(handle, url, ...) : 
      Must specify at least one of url or handle

This error is non-fatal as the app carries on and choose another sheet.

It occurs when I fetch this sheet, [Ari's Anchor Text Scraper](https://docs.google.com/a/markedmondson.me/spreadsheet/ccc?key=0Av8m6X4cYe9hdFFLU1lWUndCWHNzVWZZRWFNZHQtYXc&authkey=CPH0_NMF#gid=2)

Its a public sheet with lots of cells and weird formatting, so not that surprising. 

## error 2:

This is when I try to fetch the work sheet from this [MeasureCamp sheet](https://docs.google.com/a/markedmondson.me/spreadsheets/d/10RqUOHuieOtW5baYJXBdIBECjnVKTORlBmglgGd2l_c/edit#gid=0)

It crashes the app, with these messages when I try to fetch via:

    Warning: Unhandled error in observer: attempt to set an attribute on NULL
    observe({
        validate(need(sheet(), "Pick Sheet"))
        tabs <- list_ws(sheet())
        if (!is.null(tabs)) {
            choice <- names(tabs)
            names(choice) <- tabs
            updateSelectInput(session, "tab_choice", choices = choice)
        }
    })

My main aim is to avoid potentially crashy sheets for now in the listings, but you may also want to see if they can be prevented.

**Comment by jennybc** [comment]
I'll look into these. The first error is from `httr` itself, so we are somehow sending it ill-formed input. The second … do I understand this correctly: the worksheets ("tabs") are not named? Or is this something about worksheet order? Maybe that will be become clear once I actually handle the examples myself.

**Comment by MarkEdmondson1234** [comment]
Yep the worksheets/tabs usually come in a named character vector with the number (1="Sheet1", 2="Blah") etc. but in some cases they do not.

**Comment by jennybc** [comment]
The first sheet is an "old" sheet, which we are finding to be problematic in general. There's a limit to how much I'm willing to do to accommodate such sheets, since Google is now forcibly converting old sheets to new sheets and it seems old sheets may not exist much longer:

https://support.google.com/docs/answer/6082736?p=new_sheets_migrate&rd=1

We've established in #92 that `get_via_csv()` does not and, indeed, can not work for old sheets. So that deals with your first example. Can you talk the owner into making this a new sheet? Or are you willing to create your own new sheet with the same info? Then everything should work.

I will look into your second example, because it's a new sheet and just seems to be something about worksheet/tab names.

**Comment by jennybc** [comment]
OK I can register your MeasureCamp sheet. And I can list the worksheets. And retrieve contents with `get_via_csv()` using worksheet index or title. These commands all work as expected for me:

```r
measurecamp_url <- "https://docs.google.com/spreadsheets/d/10RqUOHuieOtW5baYJXBdIBECjnVKTORlBmglgGd2l_c/edit#gid=0"
ss <- measurecamp_url %>% register_ss()
ss
list_ws(ss)
ss %>% get_via_csv()
ss %>% get_via_csv(2)
ss %>% get_via_csv(3)
ss %>% get_via_csv("Most prolific users")
ss %>% get_via_csv("The most popular presentation")
ss %>% get_via_csv("Editions conversations compare")
```

So I'm not sure where to go now. Has something about the sheet changed … for the better? Or do you only have the problem in Shiny? I'm hoping we can find an example where the problem appears in non-Shiny use of `googlesheets`. I have also made other changes to the package since you opened this issue, so I suppose it's possible I fixed something here w/o meaning to? Maybe you can reinstall and reproduce your error 1 and get back to me. If we can reproduce the problem, I'd like to pin it down and fix it.

**Comment by MarkEdmondson1234** [comment]
Hmm, will take a look - its weird as it works for other sheets, perhaps a datafetch was just malformed when I tried.  Will try to reproduce.

**Comment by jennybc** [comment]
Any update here? If you can't get the problem to recur, I propose you close this. You can always reopen or open a new issue if this rears its head again.

**Comment by MarkEdmondson1234** [comment]
I'll close and reopen if I can get another example.
